spring.application.name=demo

# ========== Base de Datos (H2 para desarrollo) ==========
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA + Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=false

# ========== SpringDoc OpenAPI (Swagger) ==========
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false

# ========== JWT ==========
jwt.secret=uniremington_clave_secreta_muy_fuerte_para_produccion
jwt.expiration=86400000

# ========== Logging ==========
logging.level.root=INFO
logging.level.com.uniremington.alparque=DEBUG
