package com.uniremington.alparque.model.enums;

public enum Facultad {
    BIENESTAR_ANIMAL,
    BRIGADAS_JURIDICAS,
    ASESORIA_EMPRESARIAL,
    DISENO_IMAGEN_CORPORATIVA,
    SERVICIOS_SALUD,
    CONSULTORIO_CONTABLE,
    INGENIERIA_MEDIO_AMBIENTE
}
